//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.Aplication = new HashSet<Aplication>();
            this.HistoryPrioritet = new HashSet<HistoryPrioritet>();
            this.PlaceSale = new HashSet<PlaceSale>();
        }
    
        public int IDAgent { get; set; }
        public Nullable<int> IDTypeCompany { get; set; }
        public string NameCompany { get; set; }
        public Nullable<int> IDTypeAgent { get; set; }
        public string Adress { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string FIODirector { get; set; }
        public string Telephon { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
    
        public virtual TypeAgent TypeAgent { get; set; }
        public virtual TypeCompany TypeCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aplication> Aplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryPrioritet> HistoryPrioritet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaceSale> PlaceSale { get; set; }
    }
}
