//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aplication()
        {
            this.SostavAplication = new HashSet<SostavAplication>();
        }
    
        public int IDAplication { get; set; }
        public Nullable<int> IDStatusAplicaton { get; set; }
        public Nullable<int> IDAgent { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> IDStatusPay { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual StatusAplication StatusAplication { get; set; }
        public virtual StatusPay StatusPay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SostavAplication> SostavAplication { get; set; }
    }
}
