//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryRealesProduct
    {
        public int IDRealeseProduct { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> IDPlaceSale { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual PlaceSale PlaceSale { get; set; }
        public virtual Product Product { get; set; }
    }
}
