//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaterial
    {
        public int IDProductMaterial { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> IDMaterial { get; set; }
        public Nullable<int> CountMaterial { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Product Product { get; set; }
    }
}
