//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.HistoryMinCostProduct = new HashSet<HistoryMinCostProduct>();
            this.HistoryRealesProduct = new HashSet<HistoryRealesProduct>();
            this.ProductMaterial = new HashSet<ProductMaterial>();
            this.SostavAplication = new HashSet<SostavAplication>();
        }
    
        public int IDProduct { get; set; }
        public string Name { get; set; }
        public Nullable<int> Articul { get; set; }
        public Nullable<int> MinCostForAgent { get; set; }
        public string Image { get; set; }
        public Nullable<int> IDTypeProduct { get; set; }
        public Nullable<int> CountPeopleForCreate { get; set; }
        public Nullable<int> NumberShop { get; set; }
        public string PacketSize { get; set; }
        public Nullable<int> WeightWithoutPacket { get; set; }
        public Nullable<int> WeightWithPacket { get; set; }
        public string GOST { get; set; }
        public string ISO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryMinCostProduct> HistoryMinCostProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryRealesProduct> HistoryRealesProduct { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SostavAplication> SostavAplication { get; set; }
    }
}
