//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SostavAplication
    {
        public int IDSostavAplication { get; set; }
        public Nullable<int> IDAplication { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Aplication Aplication { get; set; }
        public virtual Product Product { get; set; }
    }
}
