//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int IDSupplier { get; set; }
        public string Name { get; set; }
        public string INN { get; set; }
        public Nullable<int> IDTypeAgent { get; set; }
    
        public virtual TypeAgent TypeAgent { get; set; }
    }
}
