//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lapushok.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int IDWorker { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Passport { get; set; }
        public string BankRequzit { get; set; }
        public string ProblemWithHealth { get; set; }
        public string Family { get; set; }
        public Nullable<int> IDSpechiality { get; set; }
    
        public virtual Spechiality Spechiality { get; set; }
    }
}
